spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.151/sell?characterEncoding=utf-8&useSSL=false&useTimezone=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    password: root
#    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false&useTimezone=true
  jpa:
    show-sql: true

  redis:
    host: 192.168.1.151
    port: 6379

  #thymeleaf 模板引擎  默认一般不用配置
#  thymeleaf:
#    check-template-location: true
#    servlet:
#      content-type: text/html
#    enabled: true
#    encoding: UTF-8
#    excluded-view-names: index
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false
#    mode: HTML


  #freemarker 模板引擎 默认一般不用配置

#  freemarker:
#    template-loader-path: classpath:/templates/  #设定ftl文件路径
#    cache: false #测试环境下及时刷新页面 上线环境需要改为true
#    charset: UTF-8
#    content-type: text/html
#    check-template-location: true
#    expose-request-attributes: false
#    expose-session-attributes: false
#    request-context-attribute: request
#    suffix: .ftl



#  mvc:
#    static-path-pattern: /img/img.jpg (thyemleaf依赖替代)

#  jackson:
#    default-property-inclusion: non_null #全局配置 若返回字段为null 则不返回给前端

server:
  servlet:
    context-path: /sell

#日志输出的格式
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#file: /var/log/tomcat/sell.log



#wechat:
#  mpAppId: wx361556cc26ac4671
#  mpAppSecret: 8d8c86bd7aafa56bbd30c65b5c093417

#微信公众号测试账号
wechat:
  #----微信公众号授权-----
  mpAppId: wx6ba6afb880210b8f
  mpAppSecret: 41338b71706a08b2da62de50ad95e6a6
  #----微信公众号授权-----

  #----开放平台id-----
  openAppId: wx6ba6afbXXXX
  openAppSecret: 41338b71706a08b2da62de50ad95xxxx
  #----开放平台id-----

  #----支付-----
  mchId: 123
  mchKey: 456
  notifyUrl: http://szjz.natapp1.cc/sell/pay/notify
  #----支付-----

  #----退款-----
  keyPath: var/weixin/h5.p12
  #----退款-----


#  师兄干货的
#wechat:
#  mpAppId: wxe007de634e454627
#  mpAppSecret: ed8bcd6a5acb51382cb967f1cf19ac89
#  openAppId: wxd898fcb01713c658
#  openAppSecret: wxd898fcb01713c658
#  mchId: 1483469312
#  mchKey: C5245D70627C1F8E9964D494B0735025
#  keyPath:  F:/h5.p12 #r商户证书文件路径 用于退款
#  notifyUrl: http://szjz.natapp1.cc/sell/pay/notify

projectUrl:
  wechatMpAuthorize: http://szjz.natapp1.cc
  wechatOpenAuthorize: http://szjz.natapp1.cc
  sell: http://szjz.natapp1.cc